name: socfony
description: Socfony gRPC server
version: 1.0.0
homepage: https://socfony.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  socfonyapis: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
