name: socfony_server
description: Socfony server application.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  orm: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
