import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:socfony/auth/auth_provider.dart';

class UserProfileAppBar extends StatelessWidget {
  const UserProfileAppBar(this.userId, {super.key});

  /// Current displayed user.
  final String userId;

  @override
  Widget build(BuildContext context) {
    return SliverAppBar(
      pinned: true,
      actions: [
        _AutoGeneratedAction(userId),
      ],
    );
  }
}

/// Auto generated action.
class _AutoGeneratedAction extends ConsumerWidget {
  const _AutoGeneratedAction(this.userId);

  /// Current displayed user.
  final String userId;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return IconButton(
      icon: const Icon(Icons.edit),
      onPressed: () {
        final demo = ref.read(authenticatedProvider).value;

        print(demo);
      },
    );
  }
}
