name: socfony
description: Socfony gRPC server
version: 1.0.0
homepage: https://socfony.com
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  betid: ^1.0.0
  easysms: ^1.0.0
  grpc: ^3.0.2
  json_annotation: ^4.6.0
  pool: ^1.5.1
  postgres: ^2.4.5
  socfonyapis:
    path: ../socfonyapis

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.0
  lints: ^2.0.0
