name: socfony
description: Socfony gRPC server
version: 1.0.0
homepage: https://socfony.com
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  betid: ^1.0.0
  easysms: ^1.0.0
  grpc: ^3.0.2
  json_annotation: ^4.6.0
  orm: ^2.2.2
  rc: ^0.1.0
  socfonyapis: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  lints: ^2.0.0

dependency_overrides:
  socfonyapis:
    path: ../socfonyapis

prisma:
  scehma: prisma/schema.prisma
  prismarc: .socfonyrc
