import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'account_phone_provider.dart';

/// Update account phone screen.
class UpdateAccountPhoneScreen extends StatelessWidget {
  const UpdateAccountPhoneScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const _AutoGeneratedText(),
      ),
      body: ListView(
        children: const <Widget>[
          SizedBox(height: 24),
          _CurrentPhoneOneTimePassword(),
          _NewPhoneTextField(),
          SizedBox(height: 60),
          _SubmitButton(),
        ],
      ),
    );
  }
}

class _AutoGeneratedText extends ConsumerWidget {
  const _AutoGeneratedText({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch current phone.
    final String? phone = ref.watch(accountPhoneProvider);

    // If phone is null, return set phone text.
    if (phone == null) {
      return const Text('设置手机号码');
    }

    return const Text('更换手机号码');
  }
}

/// Current phone one-time passwod
class _CurrentPhoneOneTimePassword extends ConsumerWidget {
  const _CurrentPhoneOneTimePassword({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch current phone.
    final String? phone = ref.watch(accountPhoneProvider);

    // If phone is null, return empty widget.
    if (phone == null) {
      return const SizedBox();
    }

    return ListTile(
      title: Text(phone),
      subtitle: const Text('验证当前手机号码，以便更换手机号码'),
      trailing: TextButton(
        child: const Text('验证'),
        onPressed: () {},
      ),
    );
  }
}

/// New phone text field.
class _NewPhoneTextField extends StatelessWidget {
  const _NewPhoneTextField({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(horizontal: 16),
      child: TextField(
        decoration: InputDecoration(
          labelText: '新手机号码',
          hintText: '请输入新手机号码',
        ),
      ),
    );
  }
}

/// Submit button.
class _SubmitButton extends StatelessWidget {
  const _SubmitButton({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Get current screen width.
    final double width = MediaQuery.of(context).size.width;

    return Center(
      child: ElevatedButton(
        onPressed: () {},
        style: ElevatedButton.styleFrom(
          padding: EdgeInsets.symmetric(horizontal: width * 0.25),
        ),
        child: const Text('下一步'),
      ),
    );
  }
}
